// <auto-generated />
namespace MyLiveStock.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_matriculeMisebas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_matriculeMisebas));
        
        string IMigrationMetadata.Id
        {
            get { return "201612271026084_Add_matriculeMisebas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
