// <auto-generated />
namespace MyLiveStock.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_rabbit_poids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_rabbit_poids));
        
        string IMigrationMetadata.Id
        {
            get { return "201701031606330_Add_rabbit_poids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
